# Generated by Django 5.0.13 on 2025-10-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingtransaction',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='LogIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=10, verbose_name='Тип операции')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('incoming_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.incomingtransaction', verbose_name='Операция прихода')),
                ('user_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог прихода',
                'verbose_name_plural': 'Логи прихода',
            },
        ),
        migrations.CreateModel(
            name='LogOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=10, verbose_name='Тип операции')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('outgoing_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.outgoingtransaction', verbose_name='Операция расхода')),
                ('user_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог расхода',
                'verbose_name_plural': 'Логи расхода',
            },
        ),
        migrations.CreateModel(
            name='LogStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=10, verbose_name='Тип операции')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock', verbose_name='Остаток на складе')),
                ('user_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог остатков',
                'verbose_name_plural': 'Логи остатков',
            },
        ),
    ]
