# Generated by Django 5.0.13 on 2025-10-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_incomingtransaction_warehouse_logincoming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
