# Generated by Django 4.1.7 on 2024-05-16 11:34

from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Create Warehouseman Group
    warehouseman_group, created = Group.objects.get_or_create(name='Кладовщик')

    # Define models and their permissions
    models_permissions = {
        'incomingtransaction': ['add', 'change', 'view'],
        'outgoingtransaction': ['add', 'change', 'view'],
        'stock': ['view'],
        'product': ['view'],
        'warehouse': ['view'],
        'document': ['view'],
    }

    for model_codename, perms in models_permissions.items():
        try:
            content_type = ContentType.objects.get(app_label='inventory', model=model_codename)
            for perm_codename in perms:
                permission = Permission.objects.get(
                    content_type=content_type,
                    codename=f'{perm_codename}_{model_codename}'
                )
                warehouseman_group.permissions.add(permission)
        except ContentType.DoesNotExist:
            # This can happen if the model is not yet created.
            # Handle this case gracefully.
            print(f"ContentType for {model_codename} not found. Skipping permissions.")
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_outgoingtransaction_warehouse_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
