# Generated by Django 5.0.13 on 2025-10-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи'),
        ),
    ]
