# Generated by Django 5.0.13 on 2025-10-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Минимальный остаток'),
        ),
    ]
